### ISSUE TITLE
Error when creating a blog post with no link rewrite specified

### ISSUE THREAD

**Issue by mathiashoffmann** [thirtybees/beesblog#1]
Failing to enter a link rewrite causes an error when saving, and even though the blog post is saved, neither the title or content is saved.

If no link rewrite has been manually entered, the module should create a link rewrite from the post title.

**Comment by firstred** [comment]
Thanks for the tip. It's added to 1.0.1

**Comment by yaniv14** [comment]
I think you should also address this issue when editing a blog post and clearing the link rewrite field.
It should keep the previous saved link if its empty

**Comment by Dh42** [comment]
This looks to be fixed now as well.
