### ISSUE TITLE
Meta title and description?

### ISSUE THREAD

**Issue by SeeTwoDev** [thirtybees/beesblog#10]
It seems the module doesn't have any way to specity meta title and description, could this be added? It's one of the rare instance in the platform that doesn't expose this.

**Comment by yaniv14** [comment]
Just realized that its missing.
It's very important, specially for blog pages.

**Comment by Dh42** [comment]
This should be fixed here, https://github.com/thirtybees/beesblog/commit/e4261585ec4d670ac2d7cb39b9219d4865a14f7b
