### ISSUE TITLE
Posts on the home page

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/beesblog#12]
Hi, not so long ago you added the ability to have recent posts on the home page. Your mod worked really well and thanks for that, however is it possible to make a few extra tweaks?

1. Post Image to show
2. Show truncated list of the first paragraph of the post content? or possibly the ability to specify the intro paragraph that shows on the home page
3. Ability to restrict how many images will show on the home page. I want it set at 4 however it keeps on showing 5.

My current website https://orren.co.za/ shows what I am really after.

Thanks so much

**Comment by firstred** [comment]
Probably. And we'd love to add that, but it will have to be scheduled for later. We'll keep this issue open as a reminder.

These are some good features, definitely interested in them, so thanks for your post!

**Comment by selwynorren** [comment]
Thanks so much, for your reply, I will also look into the code as well (I don't know much OOP Programming with PHP). but will see if I can contribute in some way.

Looking forward to your updates

**Comment by selwynorren** [comment]
I think I figured out how to get it done. It works on my website (https://www.orren-life.com). I have created two pull requests where I have added the code and formatting changes I have made for both recent posts on the home page as well as the side column recent posts.

I found some formatting issues with the layout and the default theme, so I have made those changes as well, however in the post item template I see there is also some formatting issues (Blog reached to the extreme right of the container with no spaces. I fixed these in my template and can share them with you as well?)

I have also just figured out how to add the first 150 characters of the blog content and strip all html tags from that as well. Ill wait for you to check the pull requests I have already done, then I will include these

**Comment by firstred** [comment]
Thanks. I will have a look.

**Comment by selwynorren** [comment]
You are awesome, thanks. I have made some more styling tweaks for the default theme, and some functionality changes for the recent posts for the home page. Can I go ahead and load them up for your review? Ill check the layout properly this time ;-)

It also means I have changed the posts image dimensions as well, to better fit the layout of the default theme

**Comment by firstred** [comment]
Sure!

**Comment by selwynorren** [comment]
Okay so I have made quite a few commits. I fix the `<div>` position error I made (So sorry about that) I updated the recent posts for the left column, updated the blog layout when view any specific post and I also updated the recent posts on the home page.

You can view it all on my website: http://www.orren-life.com/

What I did was delete the entire installation of TB, re-installed, uploaded my mods to the new installation of TB and installed the blog there. Created the relevant categories and posts again. So this is a fresh install of TB and a fresh install of my contribution to your brilliant blog system.

I have not played around with the popular posts widgets at all. It seems they are an exact copy of the recent posts, but I am not sure.

I hope everything will be in order
