### ISSUE TITLE
Sitemap not indexing Beesblog

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/beesblog#14]
Hi
seems that the sitemap module is not indexing the blog module at all, is there an option somewhere I should be activating?

**Comment by selwynorren** [comment]
Perfect thanks. I had a look and it is indeed positioned under moduleRoutes. However when I clicked edit It takes me to the transplant section and under there, there is an option for gsitemapAppendURLs
Its not installed there by default.

If I use the transplant module function and add it into that hook as well, then it does indeed index the module, but here is the result of that indexing (I have only copied the blog portion of the sitemap)

2017-10-30T23:04:42+02:00
monthly
https://orren-life.com/Journal/Array
0.1
monthly
/img/beesblog/posts/1-post_default.jpg
https://orren-life.com/Journal/Array
0.1
monthly
/img/beesblog/posts/2-post_default.jpg
https://orren-life.com/Journal/Array
0.1
monthly
/img/beesblog/posts/3-post_default.jpg
https://orren-life.com/Journal/Array
0.1
monthly
/img/beesblog/posts/4-post_default.jpg
https://orren-life.com/Journal/Array
0.1
monthly
/img/beesblog/posts/5-post_default.jpg
https://orren-life.com/Journal/Array
0.1
monthly
https://orren-life.com/Journal/Array
0.1
monthly
/img/beesblog/posts/7-post_default.jpg
https://orren-life.com/Journal/Array
0.1
monthly
/img/beesblog/posts/8-post_default.jpg
https://orren-life.com/Journal/Array
0.1
monthly
/img/beesblog/posts/9-post_default.jpg
https://orren-life.com/Journal/Array
0.1
monthly
/img/beesblog/posts/10-post_default.jpg
https://orren-life.com/Journal/Array
0.1
monthly
/img/beesblog/posts/11-post_default.jpg
https://orren-life.com/Journal/category/Array
0.1
monthly
https://orren-life.com/Journal/category/Array
0.1
monthly
https://orren-life.com/Journal/category/Array
0.1
monthly
https://orren-life.com/Journal/category/Array
0.1
monthly
https://orren-life.com/Journal/category/Array
0.1
monthly
https://orren-life.com/Journal/category/Array
0.1
monthly
https://orren-life.com/Journal/category/Array
0.1
monthly
https://orren-life.com/Journal/category/Array
0.1
monthly

**Comment by firstred** [comment]
Just noticed I gave you the wrong advice. It does not add the module's routes to the sitemap. It should implement the gSitemapAppend hook or something like that. It does not implement that hook at the moment. Will add this feature to the next version.

**Comment by selwynorren** [comment]
not a problem at all. It works rally well, except for the array in the indexed URL. I am just glad it does index the site. My Prestashop site, using smartblog does not index at all.

**Comment by firstred** [comment]
What do you mean by "Except for the array"? Can you post a raw XML or link to one?

**Comment by selwynorren** [comment]
Sure, if you check my posts the url says https://orren-life.com/Journal/category/Array. That array should be the category name and not the word array.

Here is the link to the generated xml feed:
http://orren-life.com/1_en_0_sitemap.xml

(I have not yet loaded products)

**Comment by firstred** [comment]
It looks very very strange to me. I will have a look at the sitemap module. This might have to be fixed in that one.

**Comment by firstred** [comment]
Strange. I cannot reproduce it. Which sitemap module do you use?

**Comment by firstred** [comment]
And which version?

**Comment by selwynorren** [comment]
It is indeed weird. So I am using the default one for ThirtyBees, It just says Sitemap by ThirtyBees and the version is 4.0.1

What I find interesting is the rest of the sitemap generation seems to be fine, its only with the blog module that it results in an array instead of the correct seo friendly url

**Comment by firstred** [comment]
Interesting behavior, but good to know it is only with the blog module. That narrows down the search for the cause.

**Comment by selwynorren** [comment]
lol yeah I hear you.

**Comment by selwynorren** [comment]
Fresh install of TB and Blog and I still get that array. Tried to see if I could figure anything out and only have these conclusions:

Line 439 $link['link'] = BeesBlog::getBeesBlogLink('beesblog_post', ['blog_rewrite' => $result->link_rewrite]);

If I change link_rewrite to id, then it does get the correct id of the relevant posts. and if I make the same mod to the category, then it gets the correct category id. Somehow the fact that the rewrite url is text is what returns the array word.

The other thing I found is the image url is not indexing properly either. it showing the relative link to the img directory instead of the full url

Wish I could be of further help, but I just dont know the codebase that well

**Comment by selwynorren** [comment]
Hey Michael,

Sorry to trouble, any chance you have made any progress into this? Is it the blog module or the sitemap module?

**Comment by selwynorren** [comment]
Great News I managed to fix it, Will send a pull request shortly

**Comment by firstred** [comment]
Interesting. Does the module need to be changed?

**Comment by selwynorren** [comment]
Hey Michael,
I did a small change in the beesblog.php file. I see that the location of the images for the blog is not correct and the last modified time does not display. But the seo friendly category link and teh post link itself works 100% correct.
