### ISSUE TITLE
Possible improvement in Image upload error

### ISSUE THREAD

**Issue by SeeTwoDev** [thirtybees/beesblog#2]
In the processImage function, you should change 

`if ($error = ImageManager::validateUpload($files[$postImageInput], 4000000)) {`
                `$this->errors[] = $this->l('Invalid image');`
                `return false;`

to 

`if ($error = ImageManager::validateUpload($files[$postImageInput], 4000000)) {`
                `$this->errors[] = $error;`
                `return false;`

Edit : While we're at it, why 4000000 bytes? It seems rather...arbitrary

**Comment by firstred** [comment]
Thanks. 

The limit is the same as regular image uploads, not to deviate too much from the basic behavior in the software. This limit will likely be removed in the future.

**Comment by getdatakick** [comment]
Outdated
