### ISSUE TITLE
Disqus not working properly

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/beesblog#21]
Howdy,

I think I am doing something wrong with the Disqus portion of the module. I added a comment to one of the blogs and I noticed two things

1. The comment count does not show how many comments have been added (To be fair the is only one - lol)

2. My own comment I made shows on every blog post I have on my system

**Comment by selwynorren** [comment]
Hi, does anyone perhaps have an update on this?

**Comment by Dh42** [comment]
Hey, sorry for the long delay in this, this should fix you, https://github.com/thirtybees/beesblog/commit/542283f65943f53b41a4c1e69566666ad9f2a0b6
