### ISSUE TITLE
Sitemap not linking post images correctly

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/beesblog#23]
Hi,

I have tried my best to fix this however my PHP skills are extremely limited when it comes to Thirty Bees (I only know procedural PHP). So after the fix for blog in the sitemap I see the images are being listed in the sitemap however the url is wrong. It links the image link with the domain name. For example:

<image:loc>/img/beesblog/posts/9-post_default.jpg</image:loc>
instead of
<image:loc>https://www.orren-life.com/img/beesblog/posts/9-post_default.jpg</image:loc>

This image url issue is only with the blog module

**Comment by selwynorren** [comment]
Hey Michael,

So I see in the code the following is called
$link['image'] = ['link' => Media::getMediaPath(BeesBlogPost::getImagePath($result->id))];

However this does not produce a full url it only produces the following (as an example):
/img/beesblog/posts/9-post_default.jpg

Could you perhaps give me an updated code that will produce the full url like in the products?

**Comment by Dh42** [comment]
This should be fixed here, This should be fixed here, https://github.com/thirtybees/beesblog/commit/e4261585ec4d670ac2d7cb39b9219d4865a14f7b

**Comment by selwynorren** [comment]
Lesley, how does one run the upgrade for these commits so that the database tables can be altered using the upgrade script? When I navigate to the modules, the blog does not show any upgrades available

**Comment by Dh42** [comment]
You would need to build the module from source. We haven't release the upgrade package yet, we are trying to get all the bugs at once in the module, then release the upgrade.

**Comment by selwynorren** [comment]
No problem at all, thanks for updating me. I have however noticed that the meta Title and descriptions for the main blog where a list of all the blog articles are shown, does not show at all

Fi you view this page, you will see what I mean:
https://www.orren-life.com/journal

**Comment by Dh42** [comment]
Is this on the main blog page? Not the category?

**Comment by selwynorren** [comment]
Correct yeah, should I rather create a new issue for this. I have found two bugs essentially, the main blog page is not showing the title and description. The other bug is that I have changed blog to journal for my website, however when I am on any given article, then the breadcrumbs still show the word blog

**Comment by Dh42** [comment]
It looks like the meta issue and the other issue were present before the last commits. Let me see what I can find.

**Comment by selwynorren** [comment]
you are correct, I never really noticed it until this commit to be honest

**Comment by selwynorren** [comment]
Correct yeah, should I rather create a new issue for this. I have found two bugs essentially, the main blog page is not showing the title and description. The other bug is that I have changed blog to journal for my website, however when I am on any given article, then the breadcrumbs still show the word blog

**Comment by Dh42** [comment]
I re-opened this issue, we will get them fixed with this one too.

**Comment by selwynorren** [comment]
Absolute Star Thanks Sir

**Comment by selwynorren** [comment]
Lesley, I managed to find the breadcrumb issue. Turns out its part of the translation system that was never saved properly, so please ignore that one

**Comment by getdatakick** [comment]
If I understood correctly, this issue was reopened because:

1. the main blog page is not showing the title and description - fixed by a15a51c7cdfd49067e72d90125d5ec023019dc17
2. then the breadcrumbs showing invalid word - as it turned out later this wasn't a bug related to module

So it seems to be this can be closed

**Comment by selwynorren** [comment]
> If I understood correctly, this issue was reopened because:
> 
>     1. the main blog page is not showing the title and description - fixed by [a15a51c](https://github.com/thirtybees/beesblog/commit/a15a51c7cdfd49067e72d90125d5ec023019dc17)
> 
>     2. then the breadcrumbs showing invalid word - as it turned out later this wasn't a bug related to module
> 
> 
> So it seems to be this can be closed

Howdy,

pretty much yes, however on the latter part, ill open a separate issue for it. If I change the blog name in the configuration, then I am hoping that name change would pull through everywhere and not be reliant on a translation issue
