### ISSUE TITLE
Blog last mod date in Sitemap

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/beesblog#24]
Should the last mod date (Published date) not be one of the variables in the Sitemap generation? I see this is listed on the product side. I think it may be good to do this on the blog side as well?

**Comment by Dh42** [comment]
This should be fixed here, This should be fixed here, https://github.com/thirtybees/beesblog/commit/e4261585ec4d670ac2d7cb39b9219d4865a14f7b
