### ISSUE TITLE
Lots of duplicate code

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/beesblog#26]
While looking around to find help for this: https://forum.thirtybees.com/topic/647/beesblog-module-cannot-be-installed I found that three entire modules get installed twice.

First instance appears because installing _Bees Blog_ also installs _Bees Blog Categories_, _Bees Blog Popular Posts_ and _Bees Blog Recent Posts_.

Seconds instance can be found inside the _Bees Blog_ module, in `modules/beesblog/widgets/`

Both appear to contain identical code and views, but which one is the right one?

**Comment by Captain-FLAM** [comment]
I figured out already : modules that are inside `modules/beesblog/widgets/` are automatically installed (and re-installed if you try to suppress its)

Personnaly, I don't need all, so I just delete  inside this directory the modules I don't want, before installing the "blog module"

Then, it's better to delete all of them (even after)

**Comment by Dh42** [comment]
We could use a refactoring of this module since the original developer stole a lot of code for it. https://github.com/thirtybees/beesblog/issues/30

**Comment by Captain-FLAM** [comment]
I'm already working on it (only for my use, much customizations)

I don't have time to commit (too much changes needed) but I can send you my code then, like that you can take ideas you want ...

**Comment by getdatakick** [comment]
Resolved by upgrading submodules to regular modules
