### ISSUE TITLE
Product Reference for blog entries

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/beesblog#35]
Howdy all,

Thanks so much for the hard work in the BeesBlog. It looks amazing. I was really excited about product references in the blog, however it worked opposite to what I thought it would.

So right now, when I link a product to a blog post, it shows the reference to the blog post on the product details page, however is the opposite possible?

The products referenced to rather be shown in the blog post and not the product page?

**Comment by getdatakick** [comment]
There is reverse direction as well, you can check how it looks on my [site](https://store.getdatakick.com/en/blog/conseqs-reward-customer-who-write-review).

This uses  `displayBeesBlogAfterPost` hook, so make sure your blog post template is displaying this hook. Maybe you have customized template that doesn't do so. It should look like [this](https://github.com/thirtybees/beesblog/blob/f314833de8ae5334da5072b009e98eb0ebf4d785/views/templates/front/post.tpl#L43)

**Comment by selwynorren** [comment]
> There is reverse direction as well, you can check how it looks on my [site](https://store.getdatakick.com/en/blog/conseqs-reward-customer-who-write-review).
> 
> This uses `displayBeesBlogAfterPost` hook, so make sure your blog post template is displaying this hook. Maybe you have customized template that doesn't do so. It should look like [this](https://github.com/thirtybees/beesblog/blob/f314833de8ae5334da5072b009e98eb0ebf4d785/views/templates/front/post.tpl#L43)

Thanks so much for this. I have checked and the hook is indeed in place as you recommended, however the product is not showing on the blog page. I have associated the product (only 1) to the blog post.

I have also removed the theme's module override so that it uses the main module view and it still does not show the products on that blog entry.

Your blog is doing exactly what I want to have done for mine.

P.S. I have reset the module, however I have opted to keep the content and I have a few blog entries I do not want to loose, as well as all the view history, etc. Could it be a hook not registering? The linking of the blog on the product page works well, I just want the product on the blog page

**Comment by getdatakick** [comment]
It's hard to tell. You can start troubleshooting by adding following line at the very beginning of [BeesBlogRelatedProducts:: hookDisplayBeesBlogAfterPost](https://github.com/thirtybees/beesblog/blob/f314833de8ae5334da5072b009e98eb0ebf4d785/widgets/beesblogrelatedproducts/beesblogrelatedproducts.php#L94):

```php
return 'HOOK EXECUTED';
```

If the hook is called, it will display this text into the template, just below the blog post.

**Comment by selwynorren** [comment]
> It's hard to tell. You can start troubleshooting by adding following line at the very beginning of [BeesBlogRelatedProducts:: hookDisplayBeesBlogAfterPost](https://github.com/thirtybees/beesblog/blob/f314833de8ae5334da5072b009e98eb0ebf4d785/widgets/beesblogrelatedproducts/beesblogrelatedproducts.php#L94):
> 
> ```
> return 'HOOK EXECUTED';
> ```
> 
> If the hook is called, it will display this text into the template, just below the blog post.

Thanks getdatakick,

So I did this and nothing shows at all. If I inspect the area where this should be showing, this is all I see
`<div id="beesblog-after-post" class="row">`
`::before`
`::after`
`</div>`

**Comment by selwynorren** [comment]
So it was indeed a hook issue,

After checking your code, I saw that the widget was only hooked into teh product footer and not blog footer. When I tried to transplant the module, I could not select blog footer. I reset just that one module and there it worked.

Thanks for your help

**Comment by getdatakick** [comment]
great
