### ISSUE TITLE
Latest Posts on Home Page

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/beesblog#5]
Hi,

Please can you advise how I can get the latest blog posts on my home page for thirtybees. I have almost fully transitioned my prestashop to thirtybees, however I need to show the latest posts on my home page.

Would appreciate any help

Thanks

**Comment by Dh42** [comment]
Selwyn,

this commit handles that, https://github.com/thirtybees/beesblog/commit/d7b2410d05b4781b2289a87faa458465dcef0400

**Comment by selwynorren** [comment]
You are amazing, I will test it out a little later on. I think I am very close to moving to Thirtybees permanently.

**Comment by selwynorren** [comment]
So I implemented you changes, however I was expecting to see the post image and a short summary of the article in there.

On my current Prestashop I have the blog implements from SmartDataSoft here:
www.orren.co.za

Is is perhaps possible to re-create the content seen at the bottom of my page under the title from the Journal

I tried mucking about in the code, however I am not too clued up with Coding
