### ISSUE TITLE
Sitemap includes links to blog posts for disabled language variants

### ISSUE THREAD

**Issue by papagino007** [thirtybees/beesblog#59]
Hello people, I found a bug with the Bees Blog v1.6.1 - by thirty bees under Thirtybees 1.5 Bleeding Edge (Latest).

My website is in English and French and If I create a Blog Post in English only and select (tick) English for the selection for "Available for these languages", the Blog Title and Link Rewrite fields will automatically be created for the French language using the data that is used for the English Post. (English is the default language for my site)

If I try to manually deleted the contents in those fields for the French language and click the Save or Save and Stay button, those fields will again be automatically filled with what is used for the English Post.

This is bad, because the sitemap will generate links for those Blog posts that don't exist for the French language.

Can anybody replicate this behavior and confirm that this is a bug for this module?

**Comment by getdatakick** [comment]
There's nothing wrong with saving default language content for other languages, if content was not provided in that language content.

It is essential that merchants can modify content even for languages that blog post is not available for -- this allows for creating unpublished drafts of language variant.

The only bug I see here is integration with sitemap -- this should be fix. Only links to enabled language variants should be added to sitemap. Let's fix this
